name: Go Test

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - .github/workflows/*.yaml
  pull_request:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [published, edited]

jobs:
  test-app:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run app test
        run: |
          go fmt $(go list ./... | grep -v /vendor/)
          go vet $(go list ./... | grep -v /vendor/)
          go test -race $(go list ./... | grep -v /vendor/)
